server:
  port: 8999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
